name: update

on:
  workflow_dispatch:
  schedule:
    # 日本時間の深夜0時
    - cron: '0 15 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name as environment variable
        run: echo "NEW_BRANCH_NAME=update-color-$(date '+%s')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Recreate color data
        run: pnpm create:colors

      - name: Format data
        run: pnpm fmt:colors

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: 🍱 色データを更新
          branch: ${{ env.NEW_BRANCH_NAME }}
          delete-branch: true
          title: '🍱 色データを更新'
          body: 'このPRは自動生成されました 🤖'
          add-paths: |
            data/*.ts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
